// Active (toggleable) effect resolution, focused on attack speed.
//
// "Passive" boosts (Muscle Band, Rapid-Fire Scarf base, Choice Scarf, red
// emblems) are already in computeEffectiveStats via held-item stats + the red
// set bonus, so they are NOT toggles here. The toggles are the *active* combat
// states the user previews: X-Attack, Rapid-Fire Scarf proc, ally buffs, and
// the selected Pokémon's move/ability attack-speed buffs — all default OFF.
//
// Data: src/data/attackSpeedBoosts.json (generated by
// tools/community/normalize_as_boosts.py from the community calculator).

import type { Pokemon, HeldItem, BattleItem, StatBlock } from "../types";
import boostsData from "../data/attackSpeedBoosts.json";

export type BoostSource = "item" | "move" | "ally";

export interface ActiveBoost {
  id: string; // unique within a loadout, e.g. "x-attack" or "move:Feint"
  label: string;
  asPoints: number; // additive attack-speed points when active
  source: BoostSource;
  perLevel?: number; // extra points per level above 1
  minLevel?: number; // available from this level
  maxLevel?: number; // available up to this level
  // Multiplicative stat buffs applied when active, e.g. X-Attack { attack: 0.2 }.
  statMultipliers?: Partial<Record<keyof StatBlock, number>>;
  note?: string;
}

interface GlobalItem {
  id: string;
  label: string;
  asPoints: number;
  kind: "active" | "passive" | "ally";
}
interface MoveBoost {
  source: string;
  asPoints: number;
  perLevel?: number;
  minLevel?: number;
  maxLevel?: number;
}

const GLOBALS = boostsData.globalItems as GlobalItem[];
const MOVES = boostsData.moves as Record<string, MoveBoost[]>;

const globalById = (id: string) => GLOBALS.find((g) => g.id === id);

/** Is a level-gated boost available at this level? */
export function boostAvailableAtLevel(b: { minLevel?: number; maxLevel?: number }, level: number): boolean {
  if (b.minLevel != null && level < b.minLevel) return false;
  if (b.maxLevel != null && level > b.maxLevel) return false;
  return true;
}

/** Points a single boost contributes at a given level (includes per-level scaling). */
export function boostPointsAtLevel(b: ActiveBoost, level: number): number {
  if (!boostAvailableAtLevel(b, level)) return 0;
  return b.asPoints + (b.perLevel ? b.perLevel * (level - 1) : 0);
}

/**
 * The toggleable active boosts relevant to a loadout: X-Attack (if that battle
 * item is equipped), RFS proc (if Rapid-Fire Scarf is held), ally buffs, and
 * the selected Pokémon's move/ability buffs. Default state is all-OFF.
 */
export function availableActiveBoosts(
  pokemon: Pokemon | null,
  heldItems: (HeldItem | null)[],
  battleItem: BattleItem | null,
): ActiveBoost[] {
  const out: ActiveBoost[] = [];

  if (battleItem?.id === "x-attack") {
    const g = globalById("x-attack")!;
    out.push({ id: "x-attack", label: "X Attack (active)", asPoints: g.asPoints, source: "item",
      statMultipliers: { attack: 0.2, spAttack: 0.2 },
      note: "+20% Attack, +20% Sp. Atk, +25% attack speed for 6s." });
  }
  if (heldItems.some((i) => i?.id === "rapid-fire-scarf")) {
    const g = globalById("rapid-fire-scarf-proc")!;
    out.push({ id: "rfs-proc", label: "Rapid-Fire Scarf (proc)", asPoints: g.asPoints, source: "item",
      note: "After a move: next basic attacks gain attack speed." });
  }
  for (const g of GLOBALS.filter((x) => x.kind === "ally")) {
    out.push({ id: g.id, label: g.label, asPoints: g.asPoints, source: "ally" });
  }
  if (pokemon) {
    for (const m of MOVES[pokemon.displayName] ?? []) {
      out.push({
        id: `move:${m.source}`,
        label: m.source,
        asPoints: m.asPoints,
        source: "move",
        perLevel: m.perLevel,
        minLevel: m.minLevel,
        maxLevel: m.maxLevel,
      });
    }
  }
  return out;
}

/** Sum the active boosts' points at a level, given which ids are toggled on. */
export function activeAttackSpeedPoints(
  boosts: ActiveBoost[],
  activeIds: Set<string>,
  level: number,
): number {
  return boosts
    .filter((b) => activeIds.has(b.id))
    .reduce((sum, b) => sum + boostPointsAtLevel(b, level), 0);
}

/**
 * Combined multiplicative stat factors from the active boosts (e.g. X-Attack
 * → { attack: 1.2, spAttack: 1.2 }). Stacking multipliers compound. Returns a
 * factor per affected stat; absent stats are unbuffed (factor 1).
 */
export function activeStatFactors(
  boosts: ActiveBoost[],
  activeIds: Set<string>,
  level: number,
): Partial<Record<keyof StatBlock, number>> {
  const factors: Partial<Record<keyof StatBlock, number>> = {};
  for (const b of boosts) {
    if (!activeIds.has(b.id) || !b.statMultipliers) continue;
    if (!boostAvailableAtLevel(b, level)) continue;
    for (const [stat, mult] of Object.entries(b.statMultipliers) as [keyof StatBlock, number][]) {
      factors[stat] = (factors[stat] ?? 1) * (1 + mult);
    }
  }
  return factors;
}
